import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const plusJakarta = localFont({
  src: './fonts/PlusJakartaSans[wght].ttf',
  variable: '--font-plus-jakarta-sans',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakarta.className} antialiased`}>{children}</body>
    </html>
  );
}
